name: Slack Alert

on:
  push:
    branches:
      - main

jobs:
  notify:
    uses: ./.github/workflows/butabi-ci-slack.yml
    with:
      commit_sha: ${{ github.sha }}
      commit_message: ${{ github.event.head_commit.message }}
      quote: "If you build it, they will ship. 🛠️ *Field of DevOps*"
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
