name: Butabi Bot Slack CI

on:
  push:
    branches:
      - main

jobs:
  notify_push:
    uses: ./.github/workflows/butabi-ci-slack.yml
    with:
      commit: ${{ github.sha }}
      message: ${{ github.event.head_commit.message }}
    secrets: inherit
