name: Butabi CI Slack Notifier

on:
  workflow_call:
    inputs:
      commit:
        required: true
        type: string
      message:
        required: true
        type: string

jobs:
  notify-push:
    runs-on: ubuntu-latest
    steps:
      - name: 🧠 Extract Git metadata
        id: vars
        run: |
          echo "actor=${{ github.actor }}" >> $GITHUB_OUTPUT
          echo "commit_msg=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
          echo "commit_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: 🎭 Pick a comedy quote
        id: quote
        run: |
          QUOTES=(
            "What is Love? Baby don't merge me!"
            "Are you not entertained... by this push?!"
            "smokin'! 🔥 — The Mask"
            "I'm a peacock, you gotta let me deploy! 🦚 — The Other Guys"
            "If you build it, they will ship. 🚀 — Field of DevOps"
          )
          RANDOM_INDEX=$((RANDOM % ${#QUOTES[@]}))
          echo "random_quote=${QUOTES[$RANDOM_INDEX]}" >> $GITHUB_OUTPUT

      - name: 📣 Send Slack message
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": ":rocket: *GitHub Action Alert*",
              "attachments": [
                {
                  "color": "#36a64f",
                  "fields": [
                    {
                      "title": "Commit Author",
                      "value": "${{ steps.vars.outputs.actor }}",
                      "short": true
                    },
                    {
                      "title": "Commit SHA",
                      "value": "${{ steps.vars.outputs.commit_sha }}",
                      "short": true
                    },
                    {
                      "title": "Message",
                      "value": "${{ inputs.message }}",
                      "short": false
                    },
                    {
                      "title": "Quote of the Run",
                      "value": "${{ steps.quote.outputs.random_quote }}",
                      "short": false
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
