name: Slack Alert

on:
  push:
    branches:
      - main

jobs:
  notify:
    uses: ./.github/workflows/butabi-ci-slack.yml
    with:
      message: "🚀 New push by a Code Gladiator! Prepare for CI glory!"
      webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
