name: Butabi

on:
  push:
    branches:
      - main

jobs:
  notify:
    uses: ./.github/workflows/butabi-ci-slack.yml
    with:
      commit: ${{ github.sha }}
      message: ${{ github.event.head_commit.message }}
